### PR TITLE
Update _index.md to refer to queue instead of execute

### PR DESCRIPTION
**Pull request by eltmon**
### Prerequisites for Code Changes

* [ ] This pull request follows the code style of the project
* [ ] I have tested this feature

...

### Changes Proposed

* [Change 1]
* [Change 2]

...

### CODE REVIEW

**Comment by PhilippHeuer** [comment]
This section is about synchronous execution, so execute is correct here.

**Comment by eltmon** [comment]
No, that section was about asynchronous execution, so it should be queue(), not execute(). Please take another look.

**Comment by PhilippHeuer** [comment]
You'r right about that - sorry. I mistook the section because the code looked like the synchronous one.

The .queued() method is correct here as you say, but we still need to change the return type to `Future<>`.

**Comment by PhilippHeuer** [comment]
I pushed a commit to update the return types, the async examples should be correct now.

**Review by iProdigy — APPROVED** [review]
Thanks for pointing this out

**Review by PhilippHeuer — APPROVED** [review]

**Pull request merged**
